### ISSUE TITLE
error: ‘string’ in namespace ‘std’ does not name a type

### ISSUE THREAD

**Issue by Tete-Xiao** [CoppeliaRobotics/vrep#2]
Another compilation error occurs.

`In file included from sourceCode/inverseKinematics/geomConstraintSolver/geometricConstraintSolverInt.cpp:2:0:
sourceCode/interfaces/v_rep_internal.h:13:6: error: ‘string’ in namespace ‘std’ does not name a type
 std::string getCNameSuffixAdjustedName(const char* name);
      ^~~~~~
Makefile.Release:5314: recipe for target 'release/geometricConstraintSolverInt.o' failed`

**Comment by Coppelia** [comment]
Thanks, yes, there are a couple of small details in this transistion phase. Is fixed
